package com.finkok.facturacion.stamp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-25T11:00:58.036-06:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://facturacion.finkok.com/stamp", name = "Application")
@XmlSeeAlso({ObjectFactory.class, views.core.soap.services.apps.ObjectFactory.class})
public interface Application {

    /**
     * This method returns the status of a peding buffer invoice by using an uuid
     */
    @WebResult(name = "query_pendingResult", targetNamespace = "http://facturacion.finkok.com/stamp")
    @RequestWrapper(localName = "query_pending", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.QueryPending")
    @WebMethod(operationName = "query_pending", action = "query_pending")
    @ResponseWrapper(localName = "query_pendingResponse", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.QueryPendingResponse")
    public views.core.soap.services.apps.QueryPendingResult queryPending(
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String password,
        @WebParam(name = "uuid", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String uuid
    );

    /**
     * This function provides the stamping service to resellers
     */
    @WebResult(name = "stampResult", targetNamespace = "http://facturacion.finkok.com/stamp")
    @RequestWrapper(localName = "stamp", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.Stamp")
    @WebMethod(action = "stamp")
    @ResponseWrapper(localName = "stampResponse", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.StampResponse")
    public views.core.soap.services.apps.AcuseRecepcionCFDI stamp(
        @WebParam(name = "xml", targetNamespace = "http://facturacion.finkok.com/stamp")
        byte[] xml,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String password
    );

    /**
     * This function provides the quick stamping service to resellers
     */
    @WebResult(name = "quick_stampResult", targetNamespace = "http://facturacion.finkok.com/stamp")
    @RequestWrapper(localName = "quick_stamp", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.QuickStamp")
    @WebMethod(operationName = "quick_stamp", action = "quick_stamp")
    @ResponseWrapper(localName = "quick_stampResponse", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.QuickStampResponse")
    public views.core.soap.services.apps.AcuseRecepcionCFDI quickStamp(
        @WebParam(name = "xml", targetNamespace = "http://facturacion.finkok.com/stamp")
        byte[] xml,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String password
    );

    /**
     * This function returns the stamp information of an invoice
     */
    @WebResult(name = "stampedResult", targetNamespace = "http://facturacion.finkok.com/stamp")
    @RequestWrapper(localName = "stamped", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.Stamped")
    @WebMethod(action = "stamped")
    @ResponseWrapper(localName = "stampedResponse", targetNamespace = "http://facturacion.finkok.com/stamp", className = "com.finkok.facturacion.stamp.StampedResponse")
    public views.core.soap.services.apps.AcuseRecepcionCFDI stamped(
        @WebParam(name = "xml", targetNamespace = "http://facturacion.finkok.com/stamp")
        byte[] xml,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/stamp")
        java.lang.String password
    );
}
