package com.finkok.facturacion.cancel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-26T08:53:52.967-06:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://facturacion.finkok.com/cancel", name = "Application")
@XmlSeeAlso({views.core.soap.services.apps.ObjectFactory.class, ObjectFactory.class, com.finkok.facturacion.cancellation.ObjectFactory.class})
public interface Application {

    /**
     * This method returns the status of a peding buffer invoice by using an uuid
     */
    @WebResult(name = "query_pending_cancellationResult", targetNamespace = "http://facturacion.finkok.com/cancel")
    @RequestWrapper(localName = "query_pending_cancellation", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.QueryPendingCancellation")
    @WebMethod(operationName = "query_pending_cancellation", action = "query_pending_cancellation")
    @ResponseWrapper(localName = "query_pending_cancellationResponse", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.QueryPendingCancellationResponse")
    public views.core.soap.services.apps.QueryPendingResult queryPendingCancellation(
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String password,
        @WebParam(name = "uuid", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String uuid
    );

    /**
     * This method returns a session id for work with the webservices
     */
    @WebResult(name = "cancelResult", targetNamespace = "http://facturacion.finkok.com/cancel")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.Cancel")
    @WebMethod(action = "cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.CancelResponse")
    public views.core.soap.services.apps.CancelaCFDResult cancel(
        @WebParam(name = "UUIDS", targetNamespace = "http://facturacion.finkok.com/cancel")
        views.core.soap.services.apps.UUIDS uuids,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String password,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String taxpayerId,
        @WebParam(name = "cer", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] cer,
        @WebParam(name = "key", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] key,
        @WebParam(name = "store_pending", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.Boolean storePending
    );

    /**
     * This method returns the sat receipt (response) of the cancellation webservice
     */
    @WebResult(name = "get_receiptResult", targetNamespace = "http://facturacion.finkok.com/cancel")
    @RequestWrapper(localName = "get_receipt", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.GetReceipt")
    @WebMethod(operationName = "get_receipt", action = "get_receipt")
    @ResponseWrapper(localName = "get_receiptResponse", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.GetReceiptResponse")
    public views.core.soap.services.apps.ReceiptResult getReceipt(
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String password,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String taxpayerId,
        @WebParam(name = "uuid", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String uuid,
        @WebParam(name = "type", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String type
    );

    /**
     * This method returns a session id for work with the webservices
     */
    @WebResult(name = "out_cancelResult", targetNamespace = "http://facturacion.finkok.com/cancel")
    @RequestWrapper(localName = "out_cancel", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.OutCancel")
    @WebMethod(operationName = "out_cancel", action = "out_cancel")
    @ResponseWrapper(localName = "out_cancelResponse", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.OutCancelResponse")
    public views.core.soap.services.apps.CancelaCFDResult outCancel(
        @WebParam(name = "xml", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] xml,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String password,
        @WebParam(name = "taxpayer_id", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String taxpayerId,
        @WebParam(name = "cer", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] cer,
        @WebParam(name = "key", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] key,
        @WebParam(name = "store_pending", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.Boolean storePending
    );

    /**
     * This method cancels a CFDI by the given enveloped signature
     */
    @WebResult(name = "cancel_signatureResult", targetNamespace = "http://facturacion.finkok.com/cancel")
    @RequestWrapper(localName = "cancel_signature", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.CancelSignature")
    @WebMethod(operationName = "cancel_signature", action = "cancel_signature")
    @ResponseWrapper(localName = "cancel_signatureResponse", targetNamespace = "http://facturacion.finkok.com/cancel", className = "com.finkok.facturacion.cancel.CancelSignatureResponse")
    public views.core.soap.services.apps.CancelaCFDResult cancelSignature(
        @WebParam(name = "xml", targetNamespace = "http://facturacion.finkok.com/cancel")
        byte[] xml,
        @WebParam(name = "username", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.String password,
        @WebParam(name = "store_pending", targetNamespace = "http://facturacion.finkok.com/cancel")
        java.lang.Boolean storePending
    );
}
