package com.finkok.facturacion.cancel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-26T08:53:53.002-06:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "CancelSOAP", 
                  wsdlLocation = "http://demo-facturacion.finkok.com/servicios/soap/cancel.wsdl",
                  targetNamespace = "http://facturacion.finkok.com/cancel") 
public class CancelSOAP extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://facturacion.finkok.com/cancel", "CancelSOAP");
    public final static QName Application = new QName("http://facturacion.finkok.com/cancel", "Application");
    static {
        URL url = null;
        try {
            url = new URL("http://demo-facturacion.finkok.com/servicios/soap/cancel.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CancelSOAP.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://demo-facturacion.finkok.com/servicios/soap/cancel.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CancelSOAP(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CancelSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelSOAP() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CancelSOAP(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CancelSOAP(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CancelSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(Application, Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(Application, Application.class, features);
    }

}
